### ISSUE TITLE
Change repo name?

### ISSUE THREAD

**Issue by xomiamoore** [camunda-community-hub/camunda-7-community-helm#51]
Hello! I was having [a discussion](https://github.com/camunda-community-hub/community/issues/19) around another Helm project for the Camunda Community Hub and it was mentioned that the repo name for this project is a little confusing.

I suggest changing it to camunda-7-helm or something similar. What do you think?

**Comment by aabouzaid** [comment]
Hi @xomiamoore :wave:
I've renamed it to `camunda-7-community-helm`.

Thanks for the suggestion.
