### ISSUE TITLE
Is it possible to release ?

### ISSUE THREAD

**Issue by thecampagnards** [camunda-community-hub/camunda-7-community-helm#57]
Hello, sorry for the inconvenience, is it possible to release the latest features ? Thx !

**Comment by aabouzaid** [comment]
Hi @thecampagnards :wave:

Do you like to be one of the maintainers for this project?
It's a bit hard to find time nowadays for this project.

So probably the best way to find one more active than me to be the maintainer :sweat_smile: 
WDYT?

**Comment by thecampagnards** [comment]
Hi,
Yep nice ! if you show me few things like how to release etc. Sure I can help you to maintain this project.

Thanks !

**Comment by aabouzaid** [comment]
@thecampagnards the release is simple, when you are fine with the current master, create a new branch with the prefix `release` (e.g. `release-v7.6.2` and push it to the repo, which will trigger the [release pipeline](https://github.com/camunda-community-hub/camunda-7-community-helm/blob/bdf3a183c907d2083febbe460c433677e31f0d59/.github/workflows/release.yaml#LL1C1-L1C1).

The release notes are auto-generated based on the commit message using [chglog](https://github.com/camunda-community-hub/camunda-7-community-helm/tree/main/.chglog). The only thing you need to be aware of, if a comment doesn't follow the convention, it will not show in the release notes (so it's always better to squash the comments in the PR and use the proper title if not used).

That's it :grin:

**Comment by thecampagnards** [comment]
Okey it's simple perfect 😃
