### ISSUE TITLE
Possible to add a CA certificate?

### ISSUE THREAD

**Issue by timvdh** [camunda-community-hub/camunda-7-community-helm#62]
Our workflows access internal rest apis via https and therefore we need to configure custom CA certificates. Is this possible with the helm chart somehow or is there another recommended way to copy the CA into the container and update certificates without building a custom docker image?

**Comment by thecampagnards** [comment]
Hello, I don't really understand your need, you need to expose outside your k8s in https if that's the case check the ingress conf, if you need to expose inside your k8s in https/mtls I suggest a mesh service that will manage it for you.
